### ISSUE TITLE
Connections errors, and we also cannot exhibit the animation below. 

### ISSUE THREAD

**Issue by YANGGANG1971** [vvv-school/tutorial_inverse-kinematics#1]
The port /tutorial_inverse_kinematics-robot/environment:o and port environment can not be connected.  It is run on the Ubuntu system. But while running on Gitpod, it is OK. Do you know the reason?

![image](https://user-images.githubusercontent.com/55526431/69211032-097bc280-0ba0-11ea-89f3-5b0d09915d7d.png)

Also, we cannot see the animation as the tutorial showed.

![image](https://user-images.githubusercontent.com/55526431/69211036-0da7e000-0ba0-11ea-87b3-bca03977ddc4.png)

**Comment by pattacini** [comment]
Hi @YANGGANG1971 

As I already said before, I'm only able to test the code within Gitpod as of now. Therein, it's working gracefully. This might depend on your local installation.

To run the tutorial and see the animation, do for example:
```sh
$ yarp rpc /tutorial_inverse-kinematics-controller/cmd:rpc
>> target 100 100
>> mode t
```

If you find instructions a bit limited, it was because all these exercises are meant to be run with the presence of a tutor. In the future, we may consider extending the course in order to make it doable on its own.

**Comment by YANGGANG1971** [comment]
Yes, it can run on Gitpod correctly. But, indeed, it can not be run on Linux (no animation).

**Comment by YANGGANG1971** [comment]
Often, the Gitpod can not connect to the server... It is a pity. 
If the tutorial or assignment has a more elaborated explanation, it will be beneficial for online learning without a tutor. 
If you need my help, do not hesitate to tell me.

**Comment by pattacini** [comment]
Gitpod relies on Linux, so I would definitely rule out any problem related to the OS. Further, personally, I'm not having any single problem with Gitpod instances: I'm afraid that it is very subjective to the particular runner they spawn.

My guess is that locally you've been experiencing an address conflict. To debug this, you could launch the modules manually from within a terminal and look for `"address conflict"` error appearing therein.

Making the assignments more self-explaining does entail a major overhaul of the system, thus a quite great effort our team would need to take coherently. To address this, we might also consider using new platforms out there like [GitHub Learning Lab](https://lab.github.com/).
