### ISSUE TITLE
Leftover in controller.cpp prevents from building the tutorial

### ISSUE THREAD

**Issue by PasMarra** [vvv-school/tutorial_inverse-kinematics#3]
While trying to build the tutorial, I noticed that the file `controller.cpp` is still including `yarp/os/LockGuard.h` that is not available anymore in recent YARP versions.

I would open a PR to fix that.

**Comment by pattacini** [comment]
Thanks for spotting it, @PasMarra 👍🏻 
Please, proceed with the related PR.
